# Generated by Django 2.2.7 on 2019-11-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='sex',
            field=models.CharField(choices=[('М', 'M'), ('Ж', 'Ж')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
