# Generated by Django 2.2.7 on 2019-11-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pets_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
