# Generated by Django 2.2.7 on 2019-11-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20191124_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='cage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Cage'),
        ),
    ]
