# Generated by Django 2.2.7 on 2019-11-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20191124_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='cage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pets.Cage'),
        ),
    ]
